/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame_package;

import conn.Quiz_Dao;
import conn.Quiz_Tao;
import java.util.ArrayList;
import java.util.Vector;
import preschool_learning.Welcome_page;

/**
 *
 * @author Sandy
 */
public class Exam_Sheet extends javax.swing.JFrame {

    private String type;
    private ArrayList ques_list;
    private int ques_no = 0;
    private Quiz_Tao qt;
    private Vector final_result = new Vector();
    private Vector ans_vector;
    private String selected_ans;

    /**
     * Creates new form Counting
     */
    public Exam_Sheet() {

        initComponents();
        setSize(710, 410);
        setLocation(250, 100);

    }

    public Exam_Sheet(String type) {
        this();
        this.type = type;
        Quiz_Dao dao = new Quiz_Dao();
        ques_list = dao.getQuestion(type);
        qt = (Quiz_Tao) ques_list.get(ques_no);
        ques.setText(qt.getQuestion());
        ans1.setText(qt.getAns1());
        ans2.setText(qt.getAns2());
        ans3.setText(qt.getAns3());
        ans4.setText(qt.getAns4());
        ques_no++;
        q_no.setText(ques_no + "");
        String titl = type.substring(0, 1).toUpperCase() + type.substring(1).toLowerCase();
        title.setText("Welcome Into " + titl + " Quiz");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        q_no = new javax.swing.JLabel();
        ques = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ans1 = new javax.swing.JRadioButton();
        ans2 = new javax.swing.JRadioButton();
        ans3 = new javax.swing.JRadioButton();
        ans4 = new javax.swing.JRadioButton();
        next_btn = new javax.swing.JButton();
        finish_btn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Counting");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setText("Q :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 75, 24, 29);
        getContentPane().add(q_no);
        q_no.setBounds(52, 75, 19, 21);
        getContentPane().add(ques);
        ques.setBounds(89, 75, 591, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(91, 148, 12, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(91, 238, 12, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("B");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(454, 149, 12, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("D");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(454, 238, 14, 22);

        buttonGroup1.add(ans1);
        getContentPane().add(ans1);
        ans1.setBounds(121, 149, 158, 21);

        buttonGroup1.add(ans2);
        getContentPane().add(ans2);
        ans2.setBounds(121, 239, 158, 21);

        buttonGroup1.add(ans3);
        getContentPane().add(ans3);
        ans3.setBounds(484, 149, 188, 21);

        buttonGroup1.add(ans4);
        getContentPane().add(ans4);
        ans4.setBounds(486, 239, 186, 21);

        next_btn.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });
        getContentPane().add(next_btn);
        next_btn.setBounds(216, 314, 63, 31);

        finish_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        finish_btn.setText("Finish");
        finish_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_btnActionPerformed(evt);
            }
        });
        getContentPane().add(finish_btn);
        finish_btn.setBounds(331, 318, 75, 27);

        title.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().add(title);
        title.setBounds(193, 16, 320, 53);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/preschool_learning/back_1.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(710, 410));
        jLabel7.setMinimumSize(new java.awt.Dimension(710, 410));
        jLabel7.setPreferredSize(new java.awt.Dimension(710, 410));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 710, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        ans_vector = new Vector();
        int no = Integer.parseInt(q_no.getText());
        if (no == ques_list.size() - 1) {
            next_btn.setEnabled(false);
//            JOptionPane.showMessageDialog(this, "Click On Finish to See Result");
        }
        if (ans1.isSelected()) {
            selected_ans = ans1.getText();
        }
        if (ans2.isSelected()) {
            selected_ans = ans2.getText();

        }
        if (ans3.isSelected()) {
            selected_ans = ans3.getText();

        }
        if (ans4.isSelected()) {
            selected_ans = ans4.getText();

        }
        ans_vector.add(ques.getText());
        ans_vector.add(selected_ans);
        ans_vector.add(qt.getC_ans());
        ans_vector.add(qt.getAlt());
        final_result.add(ans_vector);
        qt = (Quiz_Tao) ques_list.get(ques_no);
        q_no.setText(ques_no + "");

        ques.setText(qt.getQuestion());
        ans1.setText(qt.getAns1());
        ans2.setText(qt.getAns2());
        ans3.setText(qt.getAns3());
        ans4.setText(qt.getAns4());
        ques_no++;
        q_no.setText(ques_no + "");


    }//GEN-LAST:event_next_btnActionPerformed

    private void finish_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_btnActionPerformed
        // TODO add your handling code here:
        ans_vector = new Vector();
        if (ans1.isSelected()) {
            selected_ans = ans1.getText();
        }
        if (ans2.isSelected()) {
            selected_ans = ans2.getText();

        }
        if (ans3.isSelected()) {
            selected_ans = ans3.getText();

        }
        if (ans4.isSelected()) {
            selected_ans = ans4.getText();

        }
        ans_vector.add(ques.getText());
        ans_vector.add(selected_ans);
        ans_vector.add(qt.getC_ans());
        ans_vector.add(qt.getAlt());
        final_result.add(ans_vector);
        Result r = new Result(final_result);
        r.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_finish_btnActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam_Sheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ans1;
    private javax.swing.JRadioButton ans2;
    private javax.swing.JRadioButton ans3;
    private javax.swing.JRadioButton ans4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton finish_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton next_btn;
    private javax.swing.JLabel q_no;
    private javax.swing.JLabel ques;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
