/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame_package;

/**
 *
 * @author Sandy
 */
public class SelectQuiz extends javax.swing.JInternalFrame {

    /**
     * Creates new form SelectQuiz
     */
    public SelectQuiz() {
        initComponents();
        setSize(626, 455);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        math = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        month = new javax.swing.JButton();
        week = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(null);

        math.setBackground(new java.awt.Color(153, 153, 255));
        math.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        math.setText("Math");
        math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathActionPerformed(evt);
            }
        });
        getContentPane().add(math);
        math.setBounds(200, 90, 90, 40);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("English");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 90, 100, 40);

        month.setBackground(new java.awt.Color(102, 102, 255));
        month.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        month.setText("Month");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(200, 240, 100, 40);

        week.setBackground(new java.awt.Color(102, 102, 255));
        week.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        week.setText("Week");
        week.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekActionPerformed(evt);
            }
        });
        getContentPane().add(week);
        week.setBounds(420, 240, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/preschool_learning/choose.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 1091);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathActionPerformed
        // TODO add your handling code here:
        Exam_Sheet es = new Exam_Sheet("math");
        es.setVisible(true);
        setVisible(false);


    }//GEN-LAST:event_mathActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Exam_Sheet es = new Exam_Sheet("english");
        es.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        Exam_Sheet es = new Exam_Sheet("month");
        es.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_monthActionPerformed

    private void weekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekActionPerformed
        // TODO add your handling code here:
        Exam_Sheet es = new Exam_Sheet("week");
        es.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_weekActionPerformed
    public static void main(String[] args) {
        SelectQuiz sq = new SelectQuiz();
        sq.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton math;
    private javax.swing.JButton month;
    private javax.swing.JButton week;
    // End of variables declaration//GEN-END:variables
}
